# Generated by Django 4.2.30 on 2026-06-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True)),
                ('project_url', models.URLField(blank=True, verbose_name='Project URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('cover_image', models.ImageField(blank=True, upload_to='projects/covers/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the homepage featured section')),
                ('is_published', models.BooleanField(default=True, help_text='Only published projects appear on the live site')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(blank=True, to='home.technology')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
