# Generated by Django 4.2.30 on 2026-06-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_technology_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('tools', 'Tools')], default='backend', max_length=20),
        ),
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, help_text='Devicon class name (e.g. devicon-python-plain)', max_length=100),
        ),
    ]
