# Generated by Django 4.2.30 on 2026-06-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_technology_category_technology_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='whoami output (your bio)')),
                ('mission_prefix', models.TextField(blank=True, help_text="Text before focus areas in mission (e.g. 'Translating complex...')")),
                ('focus_areas', models.CharField(blank=True, help_text='Comma-separated focus areas (e.g. Web Development, API Design, Cloud Technologies)', max_length=500)),
                ('stat_1_value', models.CharField(default='01+', max_length=20)),
                ('stat_1_label', models.CharField(default='EXPERIENCE (YRS)', max_length=100)),
                ('stat_2_value', models.CharField(default='05+', max_length=20)),
                ('stat_2_label', models.CharField(default='PROJECTS DEP', max_length=100)),
                ('stat_3_value', models.CharField(default='∞', max_length=20)),
                ('stat_3_label', models.CharField(default='CAFFEINE ml', max_length=100)),
                ('operator_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('languages', models.CharField(max_length=200)),
                ('status', models.CharField(default='ONLINE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About Settings',
            },
        ),
    ]
